version: "3.5"
networks:
  default:
    external:
      name: proxy
services:
  editor:
    image: editor
    build: .
    container_name: editor
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.rule: "Host: editor.app.loc"
    volumes:
      - source: .
        target: /app
        type: bind
