version: "3.7"
services:
  editor:
    container_name: editor
    image: akilli/node
    command: su-exec app ash -c 'npm install && npm start'
    working_dir: /app
    restart: unless-stopped
    ports:
    - "8080:8080"
    volumes:
      - source: .
        target: /app
        type: bind
