/**
 * Tag Names
 *
 * @enum {string}
 */
export const TagName = Object.freeze({
    A: 'a',
    ABBR: 'abbr',
    ALL: '*',
    AUDIO: 'audio',
    B: 'b',
    BLOCK: 'app-block',
    BLOCKQUOTE: 'blockquote',
    BR: 'br',
    BUTTON: 'button',
    CITE: 'cite',
    CODE: 'code',
    DATA: 'data',
    DEL: 'del',
    DETAILS: 'details',
    DFN: 'dfn',
    DIALOG: 'editor-dialog',
    DIV: 'div',
    EDITOR: 'akilli-editor',
    EM: 'em',
    FIELDSET: 'fieldset',
    FIGCAPTION: 'figcaption',
    FIGURE: 'figure',
    FOCUSBAR: 'editor-focusbar',
    FORM: 'form',
    FORMATBAR: 'editor-formatbar',
    H2: 'h2',
    H3: 'h3',
    HR: 'hr',
    I: 'i',
    IFRAME: 'iframe',
    IMG: 'img',
    INPUT: 'input',
    INS: 'ins',
    KBD: 'kbd',
    LABEL: 'label',
    LEGEND: 'legend',
    LI: 'li',
    MARK: 'mark',
    OL: 'ol',
    P: 'p',
    PRE: 'pre',
    Q: 'q',
    ROOT: 'editor-root',
    S: 's',
    SAMP: 'samp',
    SECTION: 'section',
    SLOT: 'slot',
    SMALL: 'small',
    STRONG: 'strong',
    SUB: 'sub',
    SUMMARY: 'summary',
    SUP: 'sup',
    TABLE: 'table',
    TBODY: 'tbody',
    TD: 'td',
    TFOOT: 'tfoot',
    TH: 'th',
    THEAD: 'thead',
    TIME: 'time',
    TOOLBAR: 'editor-toolbar',
    TR: 'tr',
    U: 'u',
    UL: 'ul',
    VAR: 'var',
    VIDEO: 'video',
});
