/**
 * @enum {string}
 */
export default Object.freeze({
    AUDIO: 'audio',
    BLOCK: 'block',
    BREAK: 'break',
    CAPTION: 'caption',
    COL: 'col',
    COLGROUP: 'colgroup',
    CONTAINER: 'container',
    FIGURE: 'figure',
    FORMAT: 'format',
    HEADING: 'heading',
    IFRAME: 'iframe',
    IMAGE: 'image',
    LIST: 'list',
    LISTITEM: 'listitem',
    PARAGRAPH: 'paragraph',
    PREFORMAT: 'preformat',
    QUOTE: 'quote',
    ROOT: 'root',
    RULE: 'rule',
    SLOT: 'slot',
    SUMMARY: 'summary',
    TABLE: 'table',
    TABLECELL: 'tablecell',
    TABLEROW: 'tablerow',
    TABLESECTION: 'tablesection',
    VIDEO: 'video',
});
